services:
  facilitiesService:
    build:
      context: ./Facilities
      dockerfile: Dockerfile
    ports:
      - "5000:8081"
    environment:
    - ASPNETCORE_URLS=http://+:8081
    depends_on:
      - facilitiesdb
    networks:
      - sharednetwork
    restart: on-failure
