services:
  facilitiesservice:
    build:
      context: ./Facilities
      dockerfile: Dockerfile
    ports:
      - "5000:8081"
    environment:
    - ASPNETCORE_URLS=http://+:8081
    - Mongo__ConnectionString=mongodb://facilitiesdb:27017
    - Mongo__Database=FacilitiesDB
    depends_on:
      - facilitiesdb
    networks:
      - sharednetwork
    volumes:
      - ./Users/authproj-b6bdf-firebase-adminsdk-fbsvc-9157cbb090.json:/app/src/authproj-b6bdf-firebase-adminsdk-fbsvc-9157cbb090.json:ro
    restart: on-failure

  routeservice:
    build:
      context: ./RouteService
      dockerfile: Dockerfile
    ports:
      - "5003:8083"
    environment:
    - ASPNETCORE_URLS=http://+:8083
    - Mongo__ConnectionString=mongodb://routesdb:27017
    - Mongo__Database=RoutesDB
    depends_on:
      - routesdb
    networks:
      - sharednetwork
    volumes:
      - ./Users/authproj-b6bdf-firebase-adminsdk-fbsvc-9157cbb090.json:/app/src/authproj-b6bdf-firebase-adminsdk-fbsvc-9157cbb090.json:ro
    restart: on-failure

  usersservice:
    build:
      context: ./Users
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    environment:
    - ASPNETCORE_URLS=http://+:8080
    - ConnectionStrings__sqlConnection=Server=usersdb;Database=UsersDb;User Id=sa;Password=UserPassword123!;Encrypt=False;TrustServerCertificate=True;
    - ConnectionStrings__AzuriteConnection=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;
    - ASPNETCORE_ENVIRONMENT=Development
    - IronPdf__LicenseKey=IRONSUITE.KVUSOV.BK.RU.23297-AFD696C37C-AXZOHOC-6E2COCTYTNID-Q4DY3ZMQCZLF-3OSLB2Q4JTBV-UJ4JCWTYYWLY-NMKA4EIVDRPQ-U2SYAJMZTQSZ-3E4CBZ-TK5HDJ424RWQEA-DEPLOYMENT.TRIAL-GJKMV4.TRIAL.EXPIRES.19.OCT.2025
    depends_on:
        - usersdb
    networks:
      - sharednetwork
    volumes:
      - ./Users/authproj-b6bdf-firebase-adminsdk-fbsvc-9157cbb090.json:/app/src/authproj-b6bdf-firebase-adminsdk-fbsvc-9157cbb090.json:ro
      - ./Users/Application/ViewsModels:/app/ViewsModels
    restart: on-failure

  transportservice:
    build:
      context: ./Transport
      dockerfile: Dockerfile
    ports:
      - "5002:8082"
    environment:
    - ASPNETCORE_URLS=http://+:8082
    - Mongo__ConnectionString=mongodb://transportdb:27017
    - Mongo__Database=TransportDB
    depends_on:
      - transportdb
    networks:
      - sharednetwork
    volumes:
      - ./Users/authproj-b6bdf-firebase-adminsdk-fbsvc-9157cbb090.json:/app/src/authproj-b6bdf-firebase-adminsdk-fbsvc-9157cbb090.json:ro
    restart: on-failure

  apigateway:
    build:
      context: ./Gateway
      dockerfile: Dockerfile
    ports:
      - "5004:8084" 
    environment:
      - ASPNETCORE_URLS=http://+:8084
    networks:
      - sharednetwork
    depends_on:
      - usersservice
      - transportservice
      - routeservice
      - facilitiesservice
    restart: on-failure

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - azurite_data:/data
    environment:
      BLOB_CORS_ALLOWED_ORIGINS: "http://localhost:5173" 
      BLOB_CORS_ALLOWED_METHODS: "GET,PUT,POST,DELETE,HEAD,OPTIONS"
      BLOB_CORS_ALLOWED_HEADERS: "*"
      BLOB_CORS_EXPOSE_HEADERS: "*"
    command: "azurite-blob --blobHost 0.0.0.0 --loose"
    networks:
      - sharednetwork
    restart: always

  usersdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "UserPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    volumes:
    - uservolume:/var/opt/mssql
    networks:
      - sharednetwork

  transportdb:
    image: mongo:7.0
    restart: always
    ports:
      - "27019:27017"
    volumes:
      - mongodb_transport_data:/data/db
    networks:
      - sharednetwork

  facilitiesdb:
    image: mongo:7.0
    restart: always
    ports:
      - "27018:27017"
    networks:
      - sharednetwork
    volumes:
      - mongodb_data:/data/db

  routesdb:
    image: mongo:7.0
    restart: always
    ports:
      - "27020:27017"
    networks:
      - sharednetwork
    volumes:
      - mongodb_routes_data:/data/db

  

networks:
  sharednetwork:

volumes:
  mongodb_data:
  mongodb_routes_data:
  uservolume:
  mongodb_transport_data:
  azurite_data:
    
