services:
  facilitiesservice:
    build:
      context: ./Facilities
      dockerfile: Dockerfile
    ports:
      - "5000:8081"
    environment:
    - ASPNETCORE_URLS=http://+:8081
    - Mongo__ConnectionString=mongodb://facilitiesdb:27017
    - Mongo__Database=FacilitiesDB
    depends_on:
      - facilitiesdb
    networks:
      - sharednetwork
    restart: on-failure

  facilitiesdb:
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017"
    networks:
      - sharednetwork
    volumes:
      - mongodb_data:/data/db

networks:
  sharednetwork:

volumes:
  mongodb_data:
    
