export const config = {
    LOG_IN_URL: 'http://localhost:5004/users/login',
    SIGN_UP_URL: 'http://localhost:5004/users',
    USERS_FACILITIES_URL: 'http://localhost:5004/facility/myfacilities',
    SIGN_UP_VIA_GOOGLE_URL: 'http://localhost:5004/users/google',
    GET_FACILITIES_URL: 'http://localhost:5004/facility',
    CHANGE_FACILITIES_IMAGE_URL: 'http://localhost:5004/facility/image/',
    CREATE_FACILITY_URL: 'http://localhost:5004/facility',
    GET_TRANSPORT_URL: 'http://localhost:5004/transport', 
    GET_ALL_USERS_URL: 'http://localhost:5004/users',
    GET_USER_BY_UID_URL: 'http://localhost:5004/users/uid/',
    UPDATE_USER_ROLES_URL: 'http://localhost:5004/users/roles/',
    CHANGE_USERS_IMAGE_URL: 'http://localhost:5004/users/image',
    AZURE_USERS_URL: 'http://localhost:10000/devstoreaccount1/users-images/',
    AZURE_FACILITIES_URL: 'http://localhost:10000/devstoreaccount1/facilities-images/',
    GET_USERS_ROUTES_URL: 'http://localhost:5003/api/routes/myroutes/',
};